# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BPMKeyFinderInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BPMKeyFinderInterface(object):
    def setupUi(self, BPMKeyFinderInterface):
        BPMKeyFinderInterface.setObjectName("BPMKeyFinderInterface")
        BPMKeyFinderInterface.resize(900, 575)
        BPMKeyFinderInterface.setAcceptDrops(True)
        self.FinderCard = CardWidget(BPMKeyFinderInterface)
        self.FinderCard.setGeometry(QtCore.QRect(30, 50, 841, 460))
        self.FinderCard.setAcceptDrops(True)
        self.FinderCard.setObjectName("FinderCard")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.FinderCard)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 821, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SearchLineEdit = SearchLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchLineEdit.sizePolicy().hasHeightForWidth())
        self.SearchLineEdit.setSizePolicy(sizePolicy)
        self.SearchLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.SearchLineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.SearchLineEdit.setFont(font)
        self.SearchLineEdit.setToolTip("")
        self.SearchLineEdit.setStatusTip("")
        self.SearchLineEdit.setInputMask("")
        self.SearchLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.verticalLayout.addWidget(self.SearchLineEdit)
        self.info_table = TableWidget(self.verticalLayoutWidget)
        self.info_table.setAcceptDrops(True)
        self.info_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.info_table.setShowGrid(False)
        self.info_table.setObjectName("info_table")
        self.info_table.setColumnCount(0)
        self.info_table.setRowCount(0)
        self.info_table.horizontalHeader().setDefaultSectionSize(130)
        self.info_table.verticalHeader().setDefaultSectionSize(60)
        self.verticalLayout.addWidget(self.info_table)
        self.IndeterminateProgressBar = IndeterminateProgressBar(self.verticalLayoutWidget)
        self.IndeterminateProgressBar.setObjectName("IndeterminateProgressBar")
        self.verticalLayout.addWidget(self.IndeterminateProgressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = PrimaryPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setProperty("hasIcon", True)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.loadButton = PushButton(self.verticalLayoutWidget)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.saveButton = PushButton(self.verticalLayoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.hintLabel = TitleLabel(BPMKeyFinderInterface)
        self.hintLabel.setEnabled(True)
        self.hintLabel.setGeometry(QtCore.QRect(50, 115, 801, 315))
        self.hintLabel.setStyleSheet("QLabel\n"
"{\n"
"background:rgba(188, 188, 188, 100);\n"
"border:2px dashed rgba(47, 47, 47, 105);\n"
"}")
        self.hintLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hintLabel.setWordWrap(True)
        self.hintLabel.setProperty("lightColor", QtGui.QColor(0, 0, 0, 200))
        self.hintLabel.setProperty("pixelFontSize", 24)
        self.hintLabel.setProperty("strikeOut", False)
        self.hintLabel.setObjectName("hintLabel")

        self.retranslateUi(BPMKeyFinderInterface)
        QtCore.QMetaObject.connectSlotsByName(BPMKeyFinderInterface)

    def retranslateUi(self, BPMKeyFinderInterface):
        _translate = QtCore.QCoreApplication.translate
        BPMKeyFinderInterface.setWindowTitle(_translate("BPMKeyFinderInterface", "BPM、调性检测"))
        self.SearchLineEdit.setPlaceholderText(_translate("BPMKeyFinderInterface", "请输入搜索关键词（标题/艺术家/专辑）"))
        self.addButton.setToolTip(_translate("BPMKeyFinderInterface", "<html><head/><body><p>添加歌曲以检测BPM及音阶</p><p>支持的文件格式：.wav/.mp3/.ogg/.m4a/.flac</p></body></html>"))
        self.addButton.setText(_translate("BPMKeyFinderInterface", "添加歌曲"))
        self.loadButton.setText(_translate("BPMKeyFinderInterface", "手动加载数据"))
        self.saveButton.setToolTip(_translate("BPMKeyFinderInterface", "<html><head/><body><p>将已测出的歌曲BPM和调性保存到.csv文件中（位于data目录下）</p></body></html>"))
        self.saveButton.setText(_translate("BPMKeyFinderInterface", "保存结果到文件"))
        self.hintLabel.setText(_translate("BPMKeyFinderInterface", "释放以添加歌曲\n"
"（目前仅支持格式：*.wav/*.mp3/*.m4a/*.ogg/*.flac）"))
from qfluentwidgets import CardWidget, IndeterminateProgressBar, PrimaryPushButton, PushButton, SearchLineEdit, TableWidget, TitleLabel
