# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MetronomeInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MetronomeInterface(object):
    def setupUi(self, MetronomeInterface):
        MetronomeInterface.setObjectName("MetronomeInterface")
        MetronomeInterface.resize(900, 575)
        self.MetronomeCard = CardWidget(MetronomeInterface)
        self.MetronomeCard.setGeometry(QtCore.QRect(30, 50, 841, 460))
        self.MetronomeCard.setAcceptDrops(True)
        self.MetronomeCard.setObjectName("MetronomeCard")
        self.ElevatedCardWidget = ElevatedCardWidget(self.MetronomeCard)
        self.ElevatedCardWidget.setGeometry(QtCore.QRect(110, 220, 621, 145))
        self.ElevatedCardWidget.setObjectName("ElevatedCardWidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.ElevatedCardWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 621, 141))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bpmLargeTitleLabel = LargeTitleLabel(self.verticalLayoutWidget_3)
        self.bpmLargeTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bpmLargeTitleLabel.setObjectName("bpmLargeTitleLabel")
        self.verticalLayout_3.addWidget(self.bpmLargeTitleLabel)
        self.bpmLabel = BodyLabel(self.verticalLayoutWidget_3)
        self.bpmLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bpmLabel.setObjectName("bpmLabel")
        self.verticalLayout_3.addWidget(self.bpmLabel)
        self.hintLabel = SubtitleLabel(self.MetronomeCard)
        self.hintLabel.setGeometry(QtCore.QRect(0, 150, 841, 51))
        self.hintLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hintLabel.setObjectName("hintLabel")
        self.TitleLabel = TitleLabel(self.MetronomeCard)
        self.TitleLabel.setGeometry(QtCore.QRect(0, 49, 841, 121))
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.reButton = PushButton(self.MetronomeCard)
        self.reButton.setGeometry(QtCore.QRect(710, 400, 102, 32))
        self.reButton.setObjectName("reButton")

        self.retranslateUi(MetronomeInterface)
        QtCore.QMetaObject.connectSlotsByName(MetronomeInterface)

    def retranslateUi(self, MetronomeInterface):
        _translate = QtCore.QCoreApplication.translate
        MetronomeInterface.setWindowTitle(_translate("MetronomeInterface", "节拍器BPM"))
        self.bpmLargeTitleLabel.setText(_translate("MetronomeInterface", "___._"))
        self.bpmLabel.setText(_translate("MetronomeInterface", "BPM"))
        self.hintLabel.setText(_translate("MetronomeInterface", "按空格键测速"))
        self.TitleLabel.setText(_translate("MetronomeInterface", "节拍器BPM"))
        self.reButton.setText(_translate("MetronomeInterface", "重置"))
from qfluentwidgets import BodyLabel, CardWidget, ElevatedCardWidget, LargeTitleLabel, PushButton, SubtitleLabel, TitleLabel
