# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScaleInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScaleInterface(object):
    def setupUi(self, ScaleInterface):
        ScaleInterface.setObjectName("ScaleInterface")
        ScaleInterface.resize(900, 575)
        ScaleInterface.setStyleSheet("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(ScaleInterface)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 531, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scaleSelectionLabel = BodyLabel(self.horizontalLayoutWidget)
        self.scaleSelectionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scaleSelectionLabel.setObjectName("scaleSelectionLabel")
        self.horizontalLayout.addWidget(self.scaleSelectionLabel)
        self.CComboBox = ComboBox(self.horizontalLayoutWidget)
        self.CComboBox.setObjectName("CComboBox")
        self.horizontalLayout.addWidget(self.CComboBox)
        self.bComboBox = ComboBox(self.horizontalLayoutWidget)
        self.bComboBox.setObjectName("bComboBox")
        self.horizontalLayout.addWidget(self.bComboBox)
        self.keyComboBox = ComboBox(self.horizontalLayoutWidget)
        self.keyComboBox.setObjectName("keyComboBox")
        self.horizontalLayout.addWidget(self.keyComboBox)
        self.SwitchButton = SwitchButton(self.horizontalLayoutWidget)
        self.SwitchButton.setChecked(False)
        self.SwitchButton.setText("")
        self.SwitchButton.setOnText("")
        self.SwitchButton.setOffText("")
        self.SwitchButton.setObjectName("SwitchButton")
        self.horizontalLayout.addWidget(self.SwitchButton)
        self.ScrollArea = ScrollArea(ScaleInterface)
        self.ScrollArea.setGeometry(QtCore.QRect(0, 100, 905, 441))
        self.ScrollArea.setStyleSheet("background:transparent;\n"
"border: none;")
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 905, 1800))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 1800))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.CardWidget = CardWidget(self.scrollAreaWidgetContents_2)
        self.CardWidget.setGeometry(QtCore.QRect(-5, 0, 910, 1800))
        self.CardWidget.setObjectName("CardWidget")
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(ScaleInterface)
        QtCore.QMetaObject.connectSlotsByName(ScaleInterface)

    def retranslateUi(self, ScaleInterface):
        _translate = QtCore.QCoreApplication.translate
        ScaleInterface.setWindowTitle(_translate("ScaleInterface", "音阶查看"))
        self.scaleSelectionLabel.setText(_translate("ScaleInterface", "音阶选择"))
from qfluentwidgets import BodyLabel, CardWidget, ComboBox, ScrollArea, SwitchButton
